export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_USERS_LIST = 'GET_USERS_LIST';
export const GET_USER_PLACES_START = 'GET_USER_PLACES_START';
export const GET_USER_PLACES_SUCCESS = 'GET_USER_PLACES_SUCCESS';

export const ADD_NEW_PLACE_START = 'ADD_NEW_PLACE_START';
export const ADD_NEW_PLACE_SUCCESS = 'ADD_NEW_PLACE_SUCCESS';
export const UPLOAD_PLACE_PROGRESS = 'UPLOAD_PLACE_PROGRESS';
export const ADD_NEW_PLACE_FAIL = 'ADD_NEW_PLACE_FAIL';
export const REMOVE_PLACE = 'REMOVE_PLACE';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REMOVE_ERRORS = 'REMOVE_ERRORS';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_END = 'REGISTER_END';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
